#index:
#    path: /
#    controller: App\Controller\DefaultController::index
getBeersList:
  path: /get-beers
  controller: App\Infrastructure\Controller\GetBeerList

getDetailBeersList:
  path: /get-detail-beers
  controller: App\Infrastructure\Controller\GetBeerDetailList