#index:
#    path: /
#    controller: App\Controller\DefaultController::index

healthcheck:
  path: /health-check
  controller: App\Infrastructure\Controller\HealthCheckGetController
  methods: [GET]

getBeersList:
  path: /get-beers
  controller: App\Infrastructure\Controller\GetBeerListController
  methods: [GET]

getDetailBeersList:
  path: /get-detail-beers
  controller: App\Infrastructure\Controller\GetBeerDetailListController
  methods: [GET]
